/*
 * REGISTERS.h
 *
 * THIS FILE WAS AUTOMATICALLY GENERATED BY /auto/project/bin/rdb2tt.pl
 * -config ./reg_generator/rdb2h.yml -db reg.db
 *
 */
#ifndef _OTP_REGS_H_
#define _OTP_REGS_H_

/*
 * ROMOTP
 */

#define OTP_CTL 0xfff80800
#define OTP_CTL_dft 0x00001000

#ifndef __ASSEMBLER__
typedef volatile union {
	struct {
		ca_uint32_t rsrvd1 : 12;
		ca_uint32_t RESETB : 1; /* bits 12:12 */
		ca_uint32_t rsrvd2 : 3;
		ca_uint32_t PWR : 1; /* bits 16:16 */
		ca_uint32_t AXIPREVENT : 1; /* bits 17:17 */
		ca_uint32_t rsrvd3 : 6;
		ca_uint32_t SPACE : 5; /* bits 28:24 */
		ca_uint32_t rsrvd4 : 3;
	} bf;
	ca_uint32_t wrd;
} OTP_CTL_t;
#endif /* !__ASSEMBLER__ */

#define SPACE_DEFAULT 0x0
#define SPACE_TDECBIST 0x8
#define SPACE_WRTSBIST 0xa
#define SPACE_LOCK 0xb
#define SPACE_RGSTR 0xd
#define SPACE_BLNKBISR 0xe

#define OTP_STATUS 0xfff80804
#define OTP_STATUS_dft 0x00000000

#ifndef __ASSEMBLER__
typedef volatile union {
	struct {
		ca_uint32_t RDOPEN_STATE : 1; /* bits 0:0 */
		ca_uint32_t WROPEN_STATE : 1; /* bits 1:1 */
		ca_uint32_t LOCK : 1; /* bits 2:2 */
		ca_uint32_t SRESP : 2; /* bits 4:3 */
		ca_uint32_t rsrvd1 : 3;
		ca_uint32_t SDATA : 8; /* bits 15:8 */
		ca_uint32_t rsrvd2 : 16;
	} bf;
	ca_uint32_t wrd;
} OTP_STATUS_t;
#endif /* !__ASSEMBLER__ */

#define OTP_PROT 0xfff80808
#define OTP_PROT_dft 0x008b0000

#ifndef __ASSEMBLER__
typedef volatile union {
	struct {
		ca_uint32_t START : 11; /* bits 10:0 */
		ca_uint32_t rsrvd1 : 5;
		ca_uint32_t END : 11; /* bits 26:16 */
		ca_uint32_t rsrvd2 : 5;
	} bf;
	ca_uint32_t wrd;
} OTP_PROT_t;
#endif /* !__ASSEMBLER__ */

#define OTP_PROTEN 0xfff8080c
#define OTP_PROTEN_dft 0x00000003

#ifndef __ASSEMBLER__
typedef volatile union {
	struct {
		ca_uint32_t EN : 1; /* bits 0:0 */
		ca_uint32_t PROG : 1; /* bits 1:1 */
		ca_uint32_t rsrvd1 : 30;
	} bf;
	ca_uint32_t wrd;
} OTP_PROTEN_t;
#endif /* !__ASSEMBLER__ */

/******************************************************************
 *
 * Block declaration
 *
 ******************************************************************/

/* ROMOTP */
#ifndef __ASSEMBLER__
typedef struct {
	OTP_CTL_t CTL; /* addr: 0x00000000 */
	ca_uint32_t rsrvd1[3];
	OTP_STATUS_t STATUS; /* addr: 0x00000004 */
	ca_uint32_t rsrvd2[3];
	OTP_PROT_t PROT; /* addr: 0x00000008 */
	ca_uint32_t rsrvd3[3];
	OTP_PROTEN_t PROTEN; /* addr: 0x0000000c */
} ROMOTP_t;
#endif /* !__ASSEMBLER__ */

#endif /* _OTP_REGS_H_ */
