
/* This is RTL9603D driver files */
/*
 * ## Please DO NOT edit this file!! ##
 * This file is auto-generated from the register source files.
 * Any modifications to this file will be LOST when it is re-generated.
 *
 * ----------------------------------------------------------------
 * Copyright(c) Realtek Semiconductor Corporation, 2009
 * All rights reserved.
 *
 * $Revision:  $
 * $Date:  $
 *
 * Purpose : The RTL9603D chip driver
 *
 * Feature : RTL9603D chip driver
 *
 */

/*
 * Include Files
 */
#include <common/rt_autoconf.h>
#include <hal/chipdef/allreg.h>
#include <hal/chipdef/allmem.h>
#include <hal/chipdef/rtl9603d/rtk_rtl9603d_reg_struct.h>
#include <hal/chipdef/rtl9603d/rtk_rtl9603d_table_struct.h>
#include <hal/chipdef/chip.h>
#include <hal/chipdef/driver.h>
#include <hal/mac/drv.h>


/* RTL9603D mac driver service APIs */
rt_macdrv_t rtl9603d_macdrv =
{
    rtl9603d_init,          /* fMdrv_init        */
    rtl9603d_miim_read,     /* fMdrv_miim_read   */
    rtl9603d_miim_write,    /* fMdrv_miim_write  */
    rtl9603d_table_read,    /* fMdrv_table_read  */
    rtl9603d_table_write,   /* fMdrv_table_write */
    rtl9603d_table_clear,   /* fMdrv_table_clear */
}; /* end of rtl9603d_macdrv */


/* Definition RTL9601B Rev. A major driver */
rt_driver_t rtl9603d_a_driver =
{
    /* type            */ RT_DRIVER_RTL9603D,
    /* RTL chip ID     */ RTL9603D_CHIP_ID,
    /* RTL revision ID */ CHIP_REV_ID_A,
    /* register list   */ rtk_rtl9603d_reg_list,
    /* table list      */ rtk_rtl9603d_table_list,
    /* mac driver      */ &rtl9603d_macdrv,
    /* reg index max   */ RTL9603D_REG_LIST_END,
    /* regField index max */ RTL9603D_REGFIELD_LIST_END,
    /* table index max */ RTL9603D_TABLE_LIST_END,
}; /* end of rtl9603d_a_driver */
