
#ifndef __INC_RTL8198E_SYS_BIT_H
#define __INC_RTL8198E_SYS_BIT_H

/* Note: This is for 98C, must check */

// SYS_HW_STRAP
#define BIT_SHIFT_SYS_SEL_40M 				24
#define BIT_SYS_SEL_40M						BIT(BIT_SHIFT_SYS_SEL_40M)
#define BIT_MASK_SYS_SEL_40M				0x1
#define BIT_CTRL_SYS_SEL_40M(x)				(((x) & BIT_MASK_SYS_SEL_40M) << BIT_SHIFT_SYS_SEL_40M)


// SYS_CLK_MANAGE
#define BIT_SHIFT_SYS_ACTIVE_LX1 			12
#define BIT_SYS_ACTIVE_LX1					BIT(BIT_SHIFT_SYS_ACTIVE_LX1)
#define BIT_MASK_SYS_ACTIVE_LX1				0x1
#define BIT_CTRL_SYS_SYS_ACTIVE_LX1(x)		(((x) & BIT_MASK_SYS_ACTIVE_LX1) << BIT_SHIFT_SYS_ACTIVE_LX1)

#define BIT_SHIFT_SYS_ACTIVE_LX1_ARB 		13
#define BIT_SYS_ACTIVE_LX1_ARB				BIT(BIT_SHIFT_SYS_ACTIVE_LX1_ARB)
#define BIT_MASK_SYS_ACTIVE_LX1_ARB			0x1
#define BIT_CTRL_SYS_ACTIVE_LX1_ARB(x)		(((x) & BIT_MASK_SYS_ACTIVE_LX1_ARB) << BIT_SHIFT_SYS_ACTIVE_LX1_ARB)

#define BIT_SHIFT_SYS_ACTIVE_PCIE0 			14
#define BIT_SYS_ACTIVE_PCIE0				BIT(BIT_SHIFT_SYS_ACTIVE_PCIE0)
#define BIT_MASK_SYS_ACTIVE_PCIE0			0x1
#define BIT_CTRL_SYS_ACTIVE_PCIE0(x)		(((x) & BIT_MASK_SYS_ACTIVE_PCIE0) << BIT_SHIFT_SYS_ACTIVE_PCIE0)

#define BIT_SHIFT_SYS_ACTIVE_PCIE1 			16
#define BIT_SYS_ACTIVE_PCIE1				BIT(BIT_SHIFT_SYS_ACTIVE_PCIE1)
#define BIT_MASK_SYS_ACTIVE_PCIE1			0x1
#define BIT_CTRL_SYS_ACTIVE_PCIE1(x)		(((x) & BIT_MASK_SYS_ACTIVE_PCIE1) << BIT_SHIFT_SYS_ACTIVE_PCIE1)

#define BIT_SHIFT_SYS_ACTIVE_STI_LX1 		18
#define BIT_SYS_ACTIVE_STI_LX1				BIT(BIT_SHIFT_SYS_ACTIVE_STI_LX1)
#define BIT_MASK_SYS_ACTIVE_STI_LX1			0x1
#define BIT_CTRL_SYS_ACTIVE_STI_LX1(x)		(((x) & BIT_MASK_SYS_ACTIVE_STI_LX1) << BIT_SHIFT_SYS_ACTIVE_STI_LX1)

#define BIT_SHIFT_SYS_PCIE_RST_N			26
#define BIT_SYS_PCIE_RST_N					BIT(BIT_SHIFT_SYS_PCIE_RST_N)
#define BIT_MASK_SYS_PCIE_RST_N				0x1
#define BIT_CTRL_SYS_PCIE_RST_N(x)			(((x) & BIT_MASK_SYS_PCIE_RST_N) << BIT_SHIFT_SYS_PCIE_RST_N)

// SYS_PCIE_PHY0, SYS_PCIE_PHY1
#define BIT_SHIFT_SYS_MDRST_N				0
#define BIT_SYS_MDRST_N						BIT(BIT_SHIFT_SYS_MDRST_N)
#define BIT_MASK_SYS_MDRST_N				0x1
#define BIT_CTRL_SYS_MDRST_N(x)				(((x) & BIT_MASK_SYS_MDRST_N) << BIT_SHIFT_SYS_MDRST_N)

#define BIT_SHIFT_SYS_LOAD_DONE				1
#define BIT_SYS_LOAD_DONE					BIT(BIT_SHIFT_SYS_LOAD_DONE)
#define BIT_MASK_SYS_LOAD_DONE				0x1
#define BIT_CTRL_SYS_LOAD_DONE(x)			(((x) & BIT_MASK_SYS_LOAD_DONE) << BIT_SHIFT_SYS_LOAD_DONE)

#define BIT_SHIFT_SYS_CLK_LOAD				2
#define BIT_SYS_CLK_LOAD					BIT(BIT_SHIFT_SYS_CLK_LOAD)
#define BIT_MASK_SYS_CLK_LOAD				0x1
#define BIT_CTRL_SYS_CLK_LOAD(x)			(((x) & BIT_MASK_SYS_CLK_LOAD) << BIT_SHIFT_SYS_CLK_LOAD)

#define BIT_SHIFT_SYS_RX50_LINK				3
#define BIT_SYS_RX50_LINK					BIT(BIT_SHIFT_SYS_RX50_LINK)
#define BIT_MASK_SYS_RX50_LINK				0x1
#define BIT_CTRL_SYS_RX50_LINK(x)			(((x) & BIT_MASK_SYS_RX50_LINK) << BIT_SHIFT_SYS_RX50_LINK)


// SYS_PIN_MUX_2
#define BIT_SHIFT_SYS_REG_IOCFG_PCIE		20
#define BIT_SYS_REG_IOCFG_PCIE				BIT(BIT_SHIFT_SYS_REG_IOCFG_PCIE)
#define BIT_MASK_SYS_REG_IOCFG_PCIE			0x3
#define BIT_CTRL_SYS_REG_IOCFG_PCIE(x)		(((x) & BIT_MASK_SYS_REG_IOCFG_PCIE) << BIT_SHIFT_SYS_REG_IOCFG_PCIE)


// SYS_PIN_MUX2, REG_IOCFG_PCIE
enum _SYS_REG_IOCFG_PCIE_ {
	SYS_REG_IOCFG_PCIE_JTAG = 0,
	SYS_REG_IOCFG_PCIE_PCIE = 1,
	SYS_REG_IOCFG_PCIE_NONE = 2,
	SYS_REG_IOCFG_PCIE_GPIO = 3
};

#endif

