include $(APOLLODIR)/Compiler_Flag
include $(SDKDIR)/src/dal/ca8279/DAL_Compiler_Flag

ccflags-y := -I$(ROOTDIR)/ca_packages/ca-network-engine/1.0-r0/ca-network-engine-1.0 \
             -I$(ROOTDIR)/ca_packages/ca-plat/1.0-r0/ca-plat-1.0/inc \
             -I$(ROOTDIR)/ca_packages/ca-plat/1.0-r0/ca-plat-1.0/event \
             -I$(ROOTDIR)/ca_packages/ca-plat/1.0-r0/ca-plat-1.0/log \
             -I$(ROOTDIR)/ca_packages/ca-plat/1.0-r0 \
             -I$(ROOTDIR)/ca_packages/ca-scfg/1.0-r0/ca-scfg-1.0/scfg/include \
             -I$(ROOTDIR)/ca_packages/ca-pon-mac/1.0-r0/ca-pon-mac-1.0 \
             -I$(ROOTDIR)/sysroot-destdir/usr/include/module/ca-ne/ \
             -I$(ROOTDIR)/sysroot-destdir/usr/include/module/ca-plat/ \
             -I$(SDKDIR)/include \
             -I$(SDKDIR)/system/include \
             $(PON_CFLAGS) -DCONFIG_SDK_KERNEL_LINUX

obj-m += ca-rtk.o
ca-rtk-objs := $(DAL_OBJ)
