/*
 * ## Please DO NOT edit this file!! ##
 * This file is auto-generated from the register source files.
 * Any modifications to this file will be LOST when it is re-generated.
 *
 * ----------------------------------------------------------------
 * Copyright(c) Realtek Semiconductor Corporation, 2009-2016
 * All rights reserved.
 *
 * $Revision: 82256 $
 * $Date: 2017-09-18 12:07:02 +0800 (Mon, 18 Sep 2017) $
 *
 * Purpose : chip table declaration in the SDK.
 *
 * Feature : chip table declaration
 *
 */

/*
 * Include Files
 */
#include <common/rt_autoconf.h>
#include <hal/chipdef/allmem.h>
#include <hal/chipdef/mango/rtk_mango_table_struct.h>
#include <hal/chipdef/mango/rtk_mango_tableField_list.h>

rtk_table_t rtk_mango_table_list[] =
{
#if defined(CONFIG_SDK_CHIP_FEATURE_802_1Q_VLAN___QINQ)
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_VLAN */
        /* access table set */      0,
        /* access table type */     3,
        /* table size */            4096,
        /* total data registers */  4,
        /* total field numbers */   MANGO_VLANFIELD_LIST_END,
        /* table fields */          RTL9310_VLAN_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_VLAN_UNTAG */
        /* access table set */      3,
        /* access table type */     0,
        /* table size */            4096,
        /* total data registers */  2,
        /* total field numbers */   MANGO_VLAN_UNTAGFIELD_LIST_END,
        /* table fields */          RTL9310_VLAN_UNTAG_FIELDS
    },
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_802_1Q_VLAN___QINQ */
#if defined(CONFIG_SDK_CHIP_FEATURE_VLAN_TRANSLATION)
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_VLAN_EVC */
        /* access table set */      3,
        /* access table type */     1,
        /* table size */            1024,
        /* total data registers */  6,
        /* total field numbers */   MANGO_VLAN_EVCFIELD_LIST_END,
        /* table fields */          RTL9310_VLAN_EVC_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_VLAN_IP_BASED */
        /* access table set */      0,
        /* access table type */     4,
        /* table size */            2048,
        /* total data registers */  6,
        /* total field numbers */   MANGO_VLAN_IP_BASEDFIELD_LIST_END,
        /* table fields */          RTL9310_VLAN_IP_BASED_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_VLAN_IVC */
        /* access table set */      0,
        /* access table type */     4,
        /* table size */            2048,
        /* total data registers */  7,
        /* total field numbers */   MANGO_VLAN_IVCFIELD_LIST_END,
        /* table fields */          RTL9310_VLAN_IVC_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_VLAN_MAC_BASED */
        /* access table set */      0,
        /* access table type */     4,
        /* table size */            2048,
        /* total data registers */  6,
        /* total field numbers */   MANGO_VLAN_MAC_BASEDFIELD_LIST_END,
        /* table fields */          RTL9310_VLAN_MAC_BASED_FIELDS
    },
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_VLAN_TRANSLATION */
#if defined(CONFIG_SDK_CHIP_FEATURE_LINK_AGGREGATION)
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_LAG */
        /* access table set */      2,
        /* access table type */     0,
        /* table size */            128,
        /* total data registers */  3,
        /* total field numbers */   MANGO_LAGFIELD_LIST_END,
        /* table fields */          RTL9310_LAG_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_SRC_TRK_MAP */
        /* access table set */      0,
        /* access table type */     13,
        /* table size */            1024,
        /* total data registers */  1,
        /* total field numbers */   MANGO_SRC_TRK_MAPFIELD_LIST_END,
        /* table fields */          RTL9310_SRC_TRK_MAP_FIELDS
    },
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_LINK_AGGREGATION */
#if defined(CONFIG_SDK_CHIP_FEATURE_SPANNING_TREE)
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_MSTI */
        /* access table set */      0,
        /* access table type */     5,
        /* table size */            128,
        /* total data registers */  4,
        /* total field numbers */   MANGO_MSTIFIELD_LIST_END,
        /* table fields */          RTL9310_MSTI_FIELDS
    },
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_SPANNING_TREE */
#if defined(CONFIG_SDK_CHIP_FEATURE_PORT_ISOLATION)
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_PORT_ISO_CTRL */
        /* access table set */      2,
        /* access table type */     1,
        /* table size */            1024,
        /* total data registers */  2,
        /* total field numbers */   MANGO_PORT_ISO_CTRLFIELD_LIST_END,
        /* table fields */          RTL9310_PORT_ISO_CTRL_FIELDS
    },
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_PORT_ISOLATION */
#if defined(CONFIG_SDK_CHIP_FEATURE_MAC_FORWARDING_CONTROL)
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_L2_CAM_CB_MC */
        /* access table set */      0,
        /* access table type */     1,
        /* table size */            128,
        /* total data registers */  3,
        /* total field numbers */   MANGO_L2_CAM_CB_MCFIELD_LIST_END,
        /* table fields */          RTL9310_L2_CAM_CB_MC_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_L2_CAM_CB_UC */
        /* access table set */      0,
        /* access table type */     1,
        /* table size */            128,
        /* total data registers */  4,
        /* total field numbers */   MANGO_L2_CAM_CB_UCFIELD_LIST_END,
        /* table fields */          RTL9310_L2_CAM_CB_UC_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_L2_CAM_MC */
        /* access table set */      0,
        /* access table type */     1,
        /* table size */            128,
        /* total data registers */  4,
        /* total field numbers */   MANGO_L2_CAM_MCFIELD_LIST_END,
        /* table fields */          RTL9310_L2_CAM_MC_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_L2_CAM_UC */
        /* access table set */      0,
        /* access table type */     1,
        /* table size */            128,
        /* total data registers */  4,
        /* total field numbers */   MANGO_L2_CAM_UCFIELD_LIST_END,
        /* table fields */          RTL9310_L2_CAM_UC_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_L2_CB_MC */
        /* access table set */      0,
        /* access table type */     0,
        /* table size */            32768,
        /* total data registers */  3,
        /* total field numbers */   MANGO_L2_CB_MCFIELD_LIST_END,
        /* table fields */          RTL9310_L2_CB_MC_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_L2_CB_UC */
        /* access table set */      0,
        /* access table type */     0,
        /* table size */            32768,
        /* total data registers */  4,
        /* total field numbers */   MANGO_L2_CB_UCFIELD_LIST_END,
        /* table fields */          RTL9310_L2_CB_UC_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_L2_MC */
        /* access table set */      0,
        /* access table type */     0,
        /* table size */            32768,
        /* total data registers */  4,
        /* total field numbers */   MANGO_L2_MCFIELD_LIST_END,
        /* table fields */          RTL9310_L2_MC_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_L2_UC */
        /* access table set */      0,
        /* access table type */     0,
        /* table size */            32768,
        /* total data registers */  4,
        /* total field numbers */   MANGO_L2_UCFIELD_LIST_END,
        /* table fields */          RTL9310_L2_UC_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_MC_PMSK */
        /* access table set */      0,
        /* access table type */     2,
        /* table size */            4096,
        /* total data registers */  2,
        /* total field numbers */   MANGO_MC_PMSKFIELD_LIST_END,
        /* table fields */          RTL9310_MC_PMSK_FIELDS
    },
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_MAC_FORWARDING_CONTROL */
#if defined(CONFIG_SDK_CHIP_FEATURE_EGRESS_BANDWIDTH_CONTROL)
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_EGR_Q_BW */
        /* access table set */      4,
        /* access table type */     0,
        /* table size */            56,
        /* total data registers */  29,
        /* total field numbers */   MANGO_EGR_Q_BWFIELD_LIST_END,
        /* table fields */          RTL9310_EGR_Q_BW_FIELDS
    },
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_EGRESS_BANDWIDTH_CONTROL */
#if defined(CONFIG_SDK_CHIP_FEATURE_METER_MARKER)
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_METER */
        /* access table set */      1,
        /* access table type */     1,
        /* table size */            512,
        /* total data registers */  3,
        /* total field numbers */   MANGO_METERFIELD_LIST_END,
        /* table fields */          RTL9310_METER_FIELDS
    },
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_METER_MARKER */
#if defined(CONFIG_SDK_CHIP_FEATURE_FLOWCONTROL___BACKPRESSURE)
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_OUT_Q */
        /* access table set */      4,
        /* access table type */     1,
        /* table size */            56,
        /* total data registers */  13,
        /* total field numbers */   MANGO_OUT_QFIELD_LIST_END,
        /* table fields */          RTL9310_OUT_Q_FIELDS
    },
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_FLOWCONTROL___BACKPRESSURE */
#if defined(CONFIG_SDK_CHIP_FEATURE_REMARKING)
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_REMARK */
        /* access table set */      3,
        /* access table type */     4,
        /* table size */            1024,
        /* total data registers */  1,
        /* total field numbers */   MANGO_REMARKFIELD_LIST_END,
        /* table fields */          RTL9310_REMARK_FIELDS
    },
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_REMARKING */
#if defined(CONFIG_SDK_CHIP_FEATURE_LAYER_3_ROUTING)
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_L3_ECMP */
        /* access table set */      2,
        /* access table type */     5,
        /* table size */            256,
        /* total data registers */  6,
        /* total field numbers */   MANGO_L3_ECMPFIELD_LIST_END,
        /* table fields */          RTL9310_L3_ECMP_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_L3_EGR_INTF */
        /* access table set */      2,
        /* access table type */     8,
        /* table size */            1024,
        /* total data registers */  4,
        /* total field numbers */   MANGO_L3_EGR_INTFFIELD_LIST_END,
        /* table fields */          RTL9310_L3_EGR_INTF_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_L3_EGR_INTF_CNTR */
        /* access table set */      2,
        /* access table type */     13,
        /* table size */            1024,
        /* total data registers */  6,
        /* total field numbers */   MANGO_L3_EGR_INTF_CNTRFIELD_LIST_END,
        /* table fields */          RTL9310_L3_EGR_INTF_CNTR_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_L3_EGR_INTF_LIST */
        /* access table set */      2,
        /* access table type */     9,
        /* table size */            16384,
        /* total data registers */  2,
        /* total field numbers */   MANGO_L3_EGR_INTF_LISTFIELD_LIST_END,
        /* table fields */          RTL9310_L3_EGR_INTF_LIST_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_L3_EGR_TUNNEL_INTF_CNTR */
        /* access table set */      2,
        /* access table type */     15,
        /* table size */            384,
        /* total data registers */  4,
        /* total field numbers */   MANGO_L3_EGR_TUNNEL_INTF_CNTRFIELD_LIST_END,
        /* table fields */          RTL9310_L3_EGR_TUNNEL_INTF_CNTR_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_L3_HOST_ROUTE_IP6MC_0 */
        /* access table set */      2,
        /* access table type */     3,
        /* table size */            12288,
        /* total data registers */  4,
        /* total field numbers */   MANGO_L3_HOST_ROUTE_IP6MC_0FIELD_LIST_END,
        /* table fields */          RTL9310_L3_HOST_ROUTE_IP6MC_0_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_L3_HOST_ROUTE_IP6MC_1 */
        /* access table set */      2,
        /* access table type */     3,
        /* table size */            12288,
        /* total data registers */  4,
        /* total field numbers */   MANGO_L3_HOST_ROUTE_IP6MC_1FIELD_LIST_END,
        /* table fields */          RTL9310_L3_HOST_ROUTE_IP6MC_1_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_L3_HOST_ROUTE_IP6MC_2 */
        /* access table set */      2,
        /* access table type */     3,
        /* table size */            12288,
        /* total data registers */  2,
        /* total field numbers */   MANGO_L3_HOST_ROUTE_IP6MC_2FIELD_LIST_END,
        /* table fields */          RTL9310_L3_HOST_ROUTE_IP6MC_2_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_L3_HOST_ROUTE_IP6MC_3 */
        /* access table set */      2,
        /* access table type */     3,
        /* table size */            12288,
        /* total data registers */  2,
        /* total field numbers */   MANGO_L3_HOST_ROUTE_IP6MC_3FIELD_LIST_END,
        /* table fields */          RTL9310_L3_HOST_ROUTE_IP6MC_3_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_L3_HOST_ROUTE_IP6MC_4 */
        /* access table set */      2,
        /* access table type */     3,
        /* table size */            12288,
        /* total data registers */  2,
        /* total field numbers */   MANGO_L3_HOST_ROUTE_IP6MC_4FIELD_LIST_END,
        /* table fields */          RTL9310_L3_HOST_ROUTE_IP6MC_4_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_L3_HOST_ROUTE_IP6MC_5 */
        /* access table set */      2,
        /* access table type */     3,
        /* table size */            12288,
        /* total data registers */  2,
        /* total field numbers */   MANGO_L3_HOST_ROUTE_IP6MC_5FIELD_LIST_END,
        /* table fields */          RTL9310_L3_HOST_ROUTE_IP6MC_5_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_L3_HOST_ROUTE_IP6UC_0 */
        /* access table set */      2,
        /* access table type */     3,
        /* table size */            12288,
        /* total data registers */  4,
        /* total field numbers */   MANGO_L3_HOST_ROUTE_IP6UC_0FIELD_LIST_END,
        /* table fields */          RTL9310_L3_HOST_ROUTE_IP6UC_0_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_L3_HOST_ROUTE_IP6UC_1 */
        /* access table set */      2,
        /* access table type */     3,
        /* table size */            12288,
        /* total data registers */  2,
        /* total field numbers */   MANGO_L3_HOST_ROUTE_IP6UC_1FIELD_LIST_END,
        /* table fields */          RTL9310_L3_HOST_ROUTE_IP6UC_1_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_L3_HOST_ROUTE_IP6UC_2 */
        /* access table set */      2,
        /* access table type */     3,
        /* table size */            12288,
        /* total data registers */  2,
        /* total field numbers */   MANGO_L3_HOST_ROUTE_IP6UC_2FIELD_LIST_END,
        /* table fields */          RTL9310_L3_HOST_ROUTE_IP6UC_2_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_L3_HOST_ROUTE_IPMC_0 */
        /* access table set */      2,
        /* access table type */     3,
        /* table size */            12288,
        /* total data registers */  4,
        /* total field numbers */   MANGO_L3_HOST_ROUTE_IPMC_0FIELD_LIST_END,
        /* table fields */          RTL9310_L3_HOST_ROUTE_IPMC_0_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_L3_HOST_ROUTE_IPMC_1 */
        /* access table set */      2,
        /* access table type */     3,
        /* table size */            12288,
        /* total data registers */  4,
        /* total field numbers */   MANGO_L3_HOST_ROUTE_IPMC_1FIELD_LIST_END,
        /* table fields */          RTL9310_L3_HOST_ROUTE_IPMC_1_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_L3_HOST_ROUTE_IPUC */
        /* access table set */      2,
        /* access table type */     3,
        /* table size */            12288,
        /* total data registers */  4,
        /* total field numbers */   MANGO_L3_HOST_ROUTE_IPUCFIELD_LIST_END,
        /* table fields */          RTL9310_L3_HOST_ROUTE_IPUC_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_L3_IGR_INTF */
        /* access table set */      2,
        /* access table type */     7,
        /* table size */            1024,
        /* total data registers */  2,
        /* total field numbers */   MANGO_L3_IGR_INTFFIELD_LIST_END,
        /* table fields */          RTL9310_L3_IGR_INTF_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_L3_IGR_INTF_CNTR */
        /* access table set */      2,
        /* access table type */     12,
        /* table size */            1024,
        /* total data registers */  6,
        /* total field numbers */   MANGO_L3_IGR_INTF_CNTRFIELD_LIST_END,
        /* table fields */          RTL9310_L3_IGR_INTF_CNTR_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_L3_IGR_TUNNEL_INTF_CNTR */
        /* access table set */      2,
        /* access table type */     14,
        /* table size */            384,
        /* total data registers */  4,
        /* total field numbers */   MANGO_L3_IGR_TUNNEL_INTF_CNTRFIELD_LIST_END,
        /* table fields */          RTL9310_L3_IGR_TUNNEL_INTF_CNTR_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_L3_NEXTHOP */
        /* access table set */      2,
        /* access table type */     6,
        /* table size */            8192,
        /* total data registers */  1,
        /* total field numbers */   MANGO_L3_NEXTHOPFIELD_LIST_END,
        /* table fields */          RTL9310_L3_NEXTHOP_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_L3_PREFIX_ROUTE_IP6MC_0 */
        /* access table set */      2,
        /* access table type */     4,
        /* table size */            12288,
        /* total data registers */  6,
        /* total field numbers */   MANGO_L3_PREFIX_ROUTE_IP6MC_0FIELD_LIST_END,
        /* table fields */          RTL9310_L3_PREFIX_ROUTE_IP6MC_0_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_L3_PREFIX_ROUTE_IP6MC_1 */
        /* access table set */      2,
        /* access table type */     4,
        /* table size */            12288,
        /* total data registers */  6,
        /* total field numbers */   MANGO_L3_PREFIX_ROUTE_IP6MC_1FIELD_LIST_END,
        /* table fields */          RTL9310_L3_PREFIX_ROUTE_IP6MC_1_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_L3_PREFIX_ROUTE_IP6MC_2 */
        /* access table set */      2,
        /* access table type */     4,
        /* table size */            12288,
        /* total data registers */  4,
        /* total field numbers */   MANGO_L3_PREFIX_ROUTE_IP6MC_2FIELD_LIST_END,
        /* table fields */          RTL9310_L3_PREFIX_ROUTE_IP6MC_2_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_L3_PREFIX_ROUTE_IP6MC_3 */
        /* access table set */      2,
        /* access table type */     4,
        /* table size */            12288,
        /* total data registers */  4,
        /* total field numbers */   MANGO_L3_PREFIX_ROUTE_IP6MC_3FIELD_LIST_END,
        /* table fields */          RTL9310_L3_PREFIX_ROUTE_IP6MC_3_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_L3_PREFIX_ROUTE_IP6MC_4 */
        /* access table set */      2,
        /* access table type */     4,
        /* table size */            12288,
        /* total data registers */  4,
        /* total field numbers */   MANGO_L3_PREFIX_ROUTE_IP6MC_4FIELD_LIST_END,
        /* table fields */          RTL9310_L3_PREFIX_ROUTE_IP6MC_4_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_L3_PREFIX_ROUTE_IP6MC_5 */
        /* access table set */      2,
        /* access table type */     4,
        /* table size */            12288,
        /* total data registers */  4,
        /* total field numbers */   MANGO_L3_PREFIX_ROUTE_IP6MC_5FIELD_LIST_END,
        /* table fields */          RTL9310_L3_PREFIX_ROUTE_IP6MC_5_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_L3_PREFIX_ROUTE_IP6UC_0 */
        /* access table set */      2,
        /* access table type */     4,
        /* table size */            12288,
        /* total data registers */  6,
        /* total field numbers */   MANGO_L3_PREFIX_ROUTE_IP6UC_0FIELD_LIST_END,
        /* table fields */          RTL9310_L3_PREFIX_ROUTE_IP6UC_0_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_L3_PREFIX_ROUTE_IP6UC_1 */
        /* access table set */      2,
        /* access table type */     4,
        /* table size */            12288,
        /* total data registers */  4,
        /* total field numbers */   MANGO_L3_PREFIX_ROUTE_IP6UC_1FIELD_LIST_END,
        /* table fields */          RTL9310_L3_PREFIX_ROUTE_IP6UC_1_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_L3_PREFIX_ROUTE_IP6UC_2 */
        /* access table set */      2,
        /* access table type */     4,
        /* table size */            12288,
        /* total data registers */  4,
        /* total field numbers */   MANGO_L3_PREFIX_ROUTE_IP6UC_2FIELD_LIST_END,
        /* table fields */          RTL9310_L3_PREFIX_ROUTE_IP6UC_2_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_L3_PREFIX_ROUTE_IPMC_0 */
        /* access table set */      2,
        /* access table type */     4,
        /* table size */            12288,
        /* total data registers */  6,
        /* total field numbers */   MANGO_L3_PREFIX_ROUTE_IPMC_0FIELD_LIST_END,
        /* table fields */          RTL9310_L3_PREFIX_ROUTE_IPMC_0_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_L3_PREFIX_ROUTE_IPMC_1 */
        /* access table set */      2,
        /* access table type */     4,
        /* table size */            12288,
        /* total data registers */  6,
        /* total field numbers */   MANGO_L3_PREFIX_ROUTE_IPMC_1FIELD_LIST_END,
        /* table fields */          RTL9310_L3_PREFIX_ROUTE_IPMC_1_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_L3_PREFIX_ROUTE_IPUC */
        /* access table set */      2,
        /* access table type */     4,
        /* table size */            12288,
        /* total data registers */  6,
        /* total field numbers */   MANGO_L3_PREFIX_ROUTE_IPUCFIELD_LIST_END,
        /* table fields */          RTL9310_L3_PREFIX_ROUTE_IPUC_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_L3_ROUTER_MAC */
        /* access table set */      2,
        /* access table type */     2,
        /* table size */            1024,
        /* total data registers */  5,
        /* total field numbers */   MANGO_L3_ROUTER_MACFIELD_LIST_END,
        /* table fields */          RTL9310_L3_ROUTER_MAC_FIELDS
    },
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_LAYER_3_ROUTING */
#if defined(CONFIG_SDK_CHIP_FEATURE_IP_TUNNEL)
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_TUNNEL_START */
        /* access table set */      0,
        /* access table type */     9,
        /* table size */            384,
        /* total data registers */  2,
        /* total field numbers */   MANGO_TUNNEL_STARTFIELD_LIST_END,
        /* table fields */          RTL9310_TUNNEL_START_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_TUNNEL_START_ENCAP */
        /* access table set */      3,
        /* access table type */     5,
        /* table size */            384,
        /* total data registers */  9,
        /* total field numbers */   MANGO_TUNNEL_START_ENCAPFIELD_LIST_END,
        /* table fields */          RTL9310_TUNNEL_START_ENCAP_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_TUNNEL_START_ENCAP_1 */
        /* access table set */      3,
        /* access table type */     5,
        /* table size */            384,
        /* total data registers */  4,
        /* total field numbers */   MANGO_TUNNEL_START_ENCAP_1FIELD_LIST_END,
        /* table fields */          RTL9310_TUNNEL_START_ENCAP_1_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_TUNNEL_START_ENCAP_2 */
        /* access table set */      3,
        /* access table type */     5,
        /* table size */            384,
        /* total data registers */  4,
        /* total field numbers */   MANGO_TUNNEL_START_ENCAP_2FIELD_LIST_END,
        /* table fields */          RTL9310_TUNNEL_START_ENCAP_2_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_TUNNEL_TERMINATION */
        /* access table set */      0,
        /* access table type */     8,
        /* table size */            384,
        /* total data registers */  8,
        /* total field numbers */   MANGO_TUNNEL_TERMINATIONFIELD_LIST_END,
        /* table fields */          RTL9310_TUNNEL_TERMINATION_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_TUNNEL_TERMINATION_1 */
        /* access table set */      0,
        /* access table type */     8,
        /* table size */            384,
        /* total data registers */  7,
        /* total field numbers */   MANGO_TUNNEL_TERMINATION_1FIELD_LIST_END,
        /* table fields */          RTL9310_TUNNEL_TERMINATION_1_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_TUNNEL_TERMINATION_2 */
        /* access table set */      0,
        /* access table type */     8,
        /* table size */            384,
        /* total data registers */  7,
        /* total field numbers */   MANGO_TUNNEL_TERMINATION_2FIELD_LIST_END,
        /* table fields */          RTL9310_TUNNEL_TERMINATION_2_FIELDS
    },
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_IP_TUNNEL */
#if defined(CONFIG_SDK_CHIP_FEATURE_MPLS_VPLS)
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_MPLS_DECAP */
        /* access table set */      0,
        /* access table type */     10,
        /* table size */            2048,
        /* total data registers */  4,
        /* total field numbers */   MANGO_MPLS_DECAPFIELD_LIST_END,
        /* table fields */          RTL9310_MPLS_DECAP_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_MPLS_DECAP_CAM */
        /* access table set */      0,
        /* access table type */     11,
        /* table size */            64,
        /* total data registers */  4,
        /* total field numbers */   MANGO_MPLS_DECAP_CAMFIELD_LIST_END,
        /* table fields */          RTL9310_MPLS_DECAP_CAM_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_MPLS_ENCAP */
        /* access table set */      3,
        /* access table type */     2,
        /* table size */            2048,
        /* total data registers */  2,
        /* total field numbers */   MANGO_MPLS_ENCAPFIELD_LIST_END,
        /* table fields */          RTL9310_MPLS_ENCAP_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_MPLS_NH */
        /* access table set */      0,
        /* access table type */     12,
        /* table size */            8192,
        /* total data registers */  1,
        /* total field numbers */   MANGO_MPLS_NHFIELD_LIST_END,
        /* table fields */          RTL9310_MPLS_NH_FIELDS
    },
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_MPLS_VPLS */
#if defined(CONFIG_SDK_CHIP_FEATURE_MIB_COUNTER)
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_STAT_PORT_MIB_CNTR */
        /* access table set */      5,
        /* access table type */     0,
        /* table size */            57,
        /* total data registers */  53,
        /* total field numbers */   MANGO_STAT_PORT_MIB_CNTRFIELD_LIST_END,
        /* table fields */          RTL9310_STAT_PORT_MIB_CNTR_FIELDS
    },
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_MIB_COUNTER */
#if defined(CONFIG_SDK_CHIP_FEATURE_FLOW_BASED_COUNTER)
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_FLOW_CNTR */
        /* access table set */      1,
        /* access table type */     2,
        /* table size */            4096,
        /* total data registers */  3,
        /* total field numbers */   MANGO_FLOW_CNTRFIELD_LIST_END,
        /* table fields */          RTL9310_FLOW_CNTR_FIELDS
    },
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_FLOW_BASED_COUNTER */
#if defined(CONFIG_SDK_CHIP_FEATURE_PRIVATE_COUNTER)
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_AUTO_RECOVERY_TXERR_CNT */
        /* access table set */      5,
        /* access table type */     2,
        /* table size */            56,
        /* total data registers */  1,
        /* total field numbers */   MANGO_AUTO_RECOVERY_TXERR_CNTFIELD_LIST_END,
        /* table fields */          RTL9310_AUTO_RECOVERY_TXERR_CNT_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_STAT_PORT_PRVTE_CNTR */
        /* access table set */      5,
        /* access table type */     1,
        /* table size */            57,
        /* total data registers */  28,
        /* total field numbers */   MANGO_STAT_PORT_PRVTE_CNTRFIELD_LIST_END,
        /* table fields */          RTL9310_STAT_PORT_PRVTE_CNTR_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_STAT_PORT_PRVTE_E_Q_CNTR */
        /* access table set */      0,
        /* access table type */     14,
        /* table size */            57,
        /* total data registers */  4,
        /* total field numbers */   MANGO_STAT_PORT_PRVTE_E_Q_CNTRFIELD_LIST_END,
        /* table fields */          RTL9310_STAT_PORT_PRVTE_E_Q_CNTR_FIELDS
    },
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_PRIVATE_COUNTER */
#if defined(CONFIG_SDK_CHIP_FEATURE_ACL)
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_EACL */
        /* access table set */      1,
        /* access table type */     0,
        /* table size */            4096,
        /* total data registers */  22,
        /* total field numbers */   MANGO_EACLFIELD_LIST_END,
        /* table fields */          RTL9310_EACL_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_IACL */
        /* access table set */      1,
        /* access table type */     0,
        /* table size */            4096,
        /* total data registers */  22,
        /* total field numbers */   MANGO_IACLFIELD_LIST_END,
        /* table fields */          RTL9310_IACL_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_VACL */
        /* access table set */      1,
        /* access table type */     0,
        /* table size */            4096,
        /* total data registers */  22,
        /* total field numbers */   MANGO_VACLFIELD_LIST_END,
        /* table fields */          RTL9310_VACL_FIELDS
    },
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_ACL */
#if defined(CONFIG_SDK_CHIP_FEATURE_IP_MAC_BIDING)
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_IP_MAC_BIND */
        /* access table set */      0,
        /* access table type */     6,
        /* table size */            1024,
        /* total data registers */  4,
        /* total field numbers */   MANGO_IP_MAC_BINDFIELD_LIST_END,
        /* table fields */          RTL9310_IP_MAC_BIND_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_IP_MAC_BIND_CAM */
        /* access table set */      0,
        /* access table type */     7,
        /* table size */            64,
        /* total data registers */  4,
        /* total field numbers */   MANGO_IP_MAC_BIND_CAMFIELD_LIST_END,
        /* table fields */          RTL9310_IP_MAC_BIND_CAM_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_IP_MAC_BIND_DYN */
        /* access table set */      0,
        /* access table type */     10,
        /* table size */            2048,
        /* total data registers */  4,
        /* total field numbers */   MANGO_IP_MAC_BIND_DYNFIELD_LIST_END,
        /* table fields */          RTL9310_IP_MAC_BIND_DYN_FIELDS
    },
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_IP_MAC_BIDING */
#if defined(CONFIG_SDK_CHIP_FEATURE_OPENFLOW)
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_ACTION_BUCKET */
        /* access table set */      2,
        /* access table type */     11,
        /* table size */            8192,
        /* total data registers */  3,
        /* total field numbers */   MANGO_ACTION_BUCKETFIELD_LIST_END,
        /* table fields */          RTL9310_ACTION_BUCKET_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_FT_EGR */
        /* access table set */      1,
        /* access table type */     0,
        /* table size */            4096,
        /* total data registers */  17,
        /* total field numbers */   MANGO_FT_EGRFIELD_LIST_END,
        /* table fields */          RTL9310_FT_EGR_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_FT_IGR */
        /* access table set */      1,
        /* access table type */     0,
        /* table size */            4096,
        /* total data registers */  22,
        /* total field numbers */   MANGO_FT_IGRFIELD_LIST_END,
        /* table fields */          RTL9310_FT_IGR_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_FT_L2_CAM_FMT0_0 */
        /* access table set */      0,
        /* access table type */     1,
        /* table size */            128,
        /* total data registers */  4,
        /* total field numbers */   MANGO_FT_L2_CAM_FMT0_0FIELD_LIST_END,
        /* table fields */          RTL9310_FT_L2_CAM_FMT0_0_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_FT_L2_CAM_FMT0_1 */
        /* access table set */      0,
        /* access table type */     1,
        /* table size */            128,
        /* total data registers */  4,
        /* total field numbers */   MANGO_FT_L2_CAM_FMT0_1FIELD_LIST_END,
        /* table fields */          RTL9310_FT_L2_CAM_FMT0_1_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_FT_L2_CAM_FMT1_0 */
        /* access table set */      0,
        /* access table type */     1,
        /* table size */            128,
        /* total data registers */  4,
        /* total field numbers */   MANGO_FT_L2_CAM_FMT1_0FIELD_LIST_END,
        /* table fields */          RTL9310_FT_L2_CAM_FMT1_0_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_FT_L2_CAM_FMT1_1 */
        /* access table set */      0,
        /* access table type */     1,
        /* table size */            128,
        /* total data registers */  4,
        /* total field numbers */   MANGO_FT_L2_CAM_FMT1_1FIELD_LIST_END,
        /* table fields */          RTL9310_FT_L2_CAM_FMT1_1_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_FT_L2_CAM_FMT2_0 */
        /* access table set */      0,
        /* access table type */     1,
        /* table size */            128,
        /* total data registers */  4,
        /* total field numbers */   MANGO_FT_L2_CAM_FMT2_0FIELD_LIST_END,
        /* table fields */          RTL9310_FT_L2_CAM_FMT2_0_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_FT_L2_HASH_FMT0_0 */
        /* access table set */      0,
        /* access table type */     0,
        /* table size */            32768,
        /* total data registers */  4,
        /* total field numbers */   MANGO_FT_L2_HASH_FMT0_0FIELD_LIST_END,
        /* table fields */          RTL9310_FT_L2_HASH_FMT0_0_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_FT_L2_HASH_FMT0_1 */
        /* access table set */      0,
        /* access table type */     0,
        /* table size */            32768,
        /* total data registers */  4,
        /* total field numbers */   MANGO_FT_L2_HASH_FMT0_1FIELD_LIST_END,
        /* table fields */          RTL9310_FT_L2_HASH_FMT0_1_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_FT_L2_HASH_FMT1_0 */
        /* access table set */      0,
        /* access table type */     0,
        /* table size */            32768,
        /* total data registers */  4,
        /* total field numbers */   MANGO_FT_L2_HASH_FMT1_0FIELD_LIST_END,
        /* table fields */          RTL9310_FT_L2_HASH_FMT1_0_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_FT_L2_HASH_FMT1_1 */
        /* access table set */      0,
        /* access table type */     0,
        /* table size */            32768,
        /* total data registers */  4,
        /* total field numbers */   MANGO_FT_L2_HASH_FMT1_1FIELD_LIST_END,
        /* table fields */          RTL9310_FT_L2_HASH_FMT1_1_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_FT_L2_HASH_FMT2_0 */
        /* access table set */      0,
        /* access table type */     0,
        /* table size */            32768,
        /* total data registers */  4,
        /* total field numbers */   MANGO_FT_L2_HASH_FMT2_0FIELD_LIST_END,
        /* table fields */          RTL9310_FT_L2_HASH_FMT2_0_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_FT_L2_HASH_FMT2_1 */
        /* access table set */      0,
        /* access table type */     0,
        /* table size */            32768,
        /* total data registers */  4,
        /* total field numbers */   MANGO_FT_L2_HASH_FMT2_1FIELD_LIST_END,
        /* table fields */          RTL9310_FT_L2_HASH_FMT2_1_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_FT_L3_HASH_0 */
        /* access table set */      2,
        /* access table type */     3,
        /* table size */            12288,
        /* total data registers */  4,
        /* total field numbers */   MANGO_FT_L3_HASH_0FIELD_LIST_END,
        /* table fields */          RTL9310_FT_L3_HASH_0_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_FT_L3_HASH_1 */
        /* access table set */      2,
        /* access table type */     3,
        /* table size */            12288,
        /* total data registers */  4,
        /* total field numbers */   MANGO_FT_L3_HASH_1FIELD_LIST_END,
        /* table fields */          RTL9310_FT_L3_HASH_1_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_FT_L3_HASH_2 */
        /* access table set */      2,
        /* access table type */     3,
        /* table size */            12288,
        /* total data registers */  4,
        /* total field numbers */   MANGO_FT_L3_HASH_2FIELD_LIST_END,
        /* table fields */          RTL9310_FT_L3_HASH_2_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_FT_L3_TCAM_0 */
        /* access table set */      2,
        /* access table type */     4,
        /* table size */            12288,
        /* total data registers */  6,
        /* total field numbers */   MANGO_FT_L3_TCAM_0FIELD_LIST_END,
        /* table fields */          RTL9310_FT_L3_TCAM_0_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_FT_L3_TCAM_1 */
        /* access table set */      2,
        /* access table type */     4,
        /* table size */            12288,
        /* total data registers */  6,
        /* total field numbers */   MANGO_FT_L3_TCAM_1FIELD_LIST_END,
        /* table fields */          RTL9310_FT_L3_TCAM_1_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_FT_L3_TCAM_2 */
        /* access table set */      2,
        /* access table type */     4,
        /* table size */            12288,
        /* total data registers */  6,
        /* total field numbers */   MANGO_FT_L3_TCAM_2FIELD_LIST_END,
        /* table fields */          RTL9310_FT_L3_TCAM_2_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_GROUP_TBL */
        /* access table set */      2,
        /* access table type */     10,
        /* table size */            2048,
        /* total data registers */  1,
        /* total field numbers */   MANGO_GROUP_TBLFIELD_LIST_END,
        /* table fields */          RTL9310_GROUP_TBL_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_OF_DMAC */
        /* access table set */      0,
        /* access table type */     15,
        /* table size */            1024,
        /* total data registers */  2,
        /* total field numbers */   MANGO_OF_DMACFIELD_LIST_END,
        /* table fields */          RTL9310_OF_DMAC_FIELDS
    },
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_OPENFLOW */
#if defined(CONFIG_SDK_CHIP_FEATURE_L2_TUNNEL)
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_BSSID */
        /* access table set */      0,
        /* access table type */     10,
        /* table size */            2048,
        /* total data registers */  3,
        /* total field numbers */   MANGO_BSSIDFIELD_LIST_END,
        /* table fields */          RTL9310_BSSID_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_BSSID_CAM */
        /* access table set */      0,
        /* access table type */     11,
        /* table size */            64,
        /* total data registers */  4,
        /* total field numbers */   MANGO_BSSID_CAMFIELD_LIST_END,
        /* table fields */          RTL9310_BSSID_CAM_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_BSSID_LIST */
        /* access table set */      0,
        /* access table type */     12,
        /* table size */            8192,
        /* total data registers */  1,
        /* total field numbers */   MANGO_BSSID_LISTFIELD_LIST_END,
        /* table fields */          RTL9310_BSSID_LIST_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_BSSID_TUNNEL_START */
        /* access table set */      3,
        /* access table type */     3,
        /* table size */            2048,
        /* total data registers */  4,
        /* total field numbers */   MANGO_BSSID_TUNNEL_STARTFIELD_LIST_END,
        /* table fields */          RTL9310_BSSID_TUNNEL_START_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_CAPWAP_TUNNEL_START_0 */
        /* access table set */      0,
        /* access table type */     9,
        /* table size */            384,
        /* total data registers */  9,
        /* total field numbers */   MANGO_CAPWAP_TUNNEL_START_0FIELD_LIST_END,
        /* table fields */          RTL9310_CAPWAP_TUNNEL_START_0_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_CAPWAP_TUNNEL_START_1 */
        /* access table set */      0,
        /* access table type */     9,
        /* table size */            384,
        /* total data registers */  4,
        /* total field numbers */   MANGO_CAPWAP_TUNNEL_START_1FIELD_LIST_END,
        /* table fields */          RTL9310_CAPWAP_TUNNEL_START_1_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_L2_TNL_LST */
        /* access table set */      0,
        /* access table type */     12,
        /* table size */            8192,
        /* total data registers */  1,
        /* total field numbers */   MANGO_L2_TNL_LSTFIELD_LIST_END,
        /* table fields */          RTL9310_L2_TNL_LST_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_L2_TNL_MCAST */
        /* access table set */      0,
        /* access table type */     0,
        /* table size */            32768,
        /* total data registers */  3,
        /* total field numbers */   MANGO_L2_TNL_MCASTFIELD_LIST_END,
        /* table fields */          RTL9310_L2_TNL_MCAST_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_L2_TNL_MCAST_CAM */
        /* access table set */      0,
        /* access table type */     1,
        /* table size */            128,
        /* total data registers */  3,
        /* total field numbers */   MANGO_L2_TNL_MCAST_CAMFIELD_LIST_END,
        /* table fields */          RTL9310_L2_TNL_MCAST_CAM_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_L2_TNL_UCAST */
        /* access table set */      0,
        /* access table type */     0,
        /* table size */            32768,
        /* total data registers */  3,
        /* total field numbers */   MANGO_L2_TNL_UCASTFIELD_LIST_END,
        /* table fields */          RTL9310_L2_TNL_UCAST_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_L2_TNL_UCAST_CAM */
        /* access table set */      0,
        /* access table type */     1,
        /* table size */            128,
        /* total data registers */  3,
        /* total field numbers */   MANGO_L2_TNL_UCAST_CAMFIELD_LIST_END,
        /* table fields */          RTL9310_L2_TNL_UCAST_CAM_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_L2_TNL_VXLAN */
        /* access table set */      0,
        /* access table type */     10,
        /* table size */            2048,
        /* total data registers */  3,
        /* total field numbers */   MANGO_L2_TNL_VXLANFIELD_LIST_END,
        /* table fields */          RTL9310_L2_TNL_VXLAN_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_L2_TNL_VXLAN_CAM */
        /* access table set */      0,
        /* access table type */     11,
        /* table size */            64,
        /* total data registers */  3,
        /* total field numbers */   MANGO_L2_TNL_VXLAN_CAMFIELD_LIST_END,
        /* table fields */          RTL9310_L2_TNL_VXLAN_CAM_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_L2_TNL_VXLAN_ENCAP */
        /* access table set */      3,
        /* access table type */     3,
        /* table size */            2112,
        /* total data registers */  2,
        /* total field numbers */   MANGO_L2_TNL_VXLAN_ENCAPFIELD_LIST_END,
        /* table fields */          RTL9310_L2_TNL_VXLAN_ENCAP_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_VXLAN_TUNNEL_START_0 */
        /* access table set */      0,
        /* access table type */     9,
        /* table size */            384,
        /* total data registers */  9,
        /* total field numbers */   MANGO_VXLAN_TUNNEL_START_0FIELD_LIST_END,
        /* table fields */          RTL9310_VXLAN_TUNNEL_START_0_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_VXLAN_TUNNEL_START_1 */
        /* access table set */      0,
        /* access table type */     9,
        /* table size */            384,
        /* total data registers */  4,
        /* total field numbers */   MANGO_VXLAN_TUNNEL_START_1FIELD_LIST_END,
        /* table fields */          RTL9310_VXLAN_TUNNEL_START_1_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_WLC_MCAST */
        /* access table set */      0,
        /* access table type */     0,
        /* table size */            32768,
        /* total data registers */  3,
        /* total field numbers */   MANGO_WLC_MCASTFIELD_LIST_END,
        /* table fields */          RTL9310_WLC_MCAST_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_WLC_MCAST_CAM */
        /* access table set */      0,
        /* access table type */     1,
        /* table size */            128,
        /* total data registers */  3,
        /* total field numbers */   MANGO_WLC_MCAST_CAMFIELD_LIST_END,
        /* table fields */          RTL9310_WLC_MCAST_CAM_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_WLC_UCAST */
        /* access table set */      0,
        /* access table type */     0,
        /* table size */            32768,
        /* total data registers */  3,
        /* total field numbers */   MANGO_WLC_UCASTFIELD_LIST_END,
        /* table fields */          RTL9310_WLC_UCAST_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_WLC_UCAST_CAM */
        /* access table set */      0,
        /* access table type */     1,
        /* table size */            128,
        /* total data registers */  3,
        /* total field numbers */   MANGO_WLC_UCAST_CAMFIELD_LIST_END,
        /* table fields */          RTL9310_WLC_UCAST_CAM_FIELDS
    },
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_L2_TUNNEL */
#if defined(CONFIG_SDK_CHIP_FEATURE_PORT_EXTENSION)
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_ECID_PMSK_LIST */
        /* access table set */      0,
        /* access table type */     12,
        /* table size */            8192,
        /* total data registers */  2,
        /* total field numbers */   MANGO_ECID_PMSK_LISTFIELD_LIST_END,
        /* table fields */          RTL9310_ECID_PMSK_LIST_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_ECID_PVID */
        /* access table set */      0,
        /* access table type */     10,
        /* table size */            2048,
        /* total data registers */  2,
        /* total field numbers */   MANGO_ECID_PVIDFIELD_LIST_END,
        /* table fields */          RTL9310_ECID_PVID_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_ECID_PVID_CAM */
        /* access table set */      0,
        /* access table type */     11,
        /* table size */            64,
        /* total data registers */  2,
        /* total field numbers */   MANGO_ECID_PVID_CAMFIELD_LIST_END,
        /* table fields */          RTL9310_ECID_PVID_CAM_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_PE_FWD */
        /* access table set */      0,
        /* access table type */     0,
        /* table size */            32768,
        /* total data registers */  4,
        /* total field numbers */   MANGO_PE_FWDFIELD_LIST_END,
        /* table fields */          RTL9310_PE_FWD_FIELDS
    },
#endif
#if defined(CONFIG_SDK_RTL9310)
    {   /* table name               INT_MANGO_RTL9310_PE_FWD_CAM */
        /* access table set */      0,
        /* access table type */     1,
        /* table size */            128,
        /* total data registers */  4,
        /* total field numbers */   MANGO_PE_FWD_CAMFIELD_LIST_END,
        /* table fields */          RTL9310_PE_FWD_CAM_FIELDS
    },
#endif
#endif   /* CONFIG_SDK_CHIP_FEATURE_PORT_EXTENSION */
};

#if defined(CONFIG_SDK_DUMP_TABLE_WITH_NAME)
rtk_tableName_t rtk_mango_tableName_list[] =
{
#if defined(CONFIG_SDK_CHIP_FEATURE_802_1Q_VLAN___QINQ)
    {"VLAN"},
    {"VLAN_UNTAG"},
#endif   /* CONFIG_SDK_CHIP_FEATURE_802_1Q_VLAN___QINQ */
#if defined(CONFIG_SDK_CHIP_FEATURE_VLAN_TRANSLATION)
    {"VLAN_EVC"},
    {"VLAN_IP_BASED"},
    {"VLAN_IVC"},
    {"VLAN_MAC_BASED"},
#endif   /* CONFIG_SDK_CHIP_FEATURE_VLAN_TRANSLATION */
#if defined(CONFIG_SDK_CHIP_FEATURE_LINK_AGGREGATION)
    {"LAG"},
    {"SRC_TRK_MAP"},
#endif   /* CONFIG_SDK_CHIP_FEATURE_LINK_AGGREGATION */
#if defined(CONFIG_SDK_CHIP_FEATURE_SPANNING_TREE)
    {"MSTI"},
#endif   /* CONFIG_SDK_CHIP_FEATURE_SPANNING_TREE */
#if defined(CONFIG_SDK_CHIP_FEATURE_PORT_ISOLATION)
    {"PORT_ISO_CTRL"},
#endif   /* CONFIG_SDK_CHIP_FEATURE_PORT_ISOLATION */
#if defined(CONFIG_SDK_CHIP_FEATURE_MAC_FORWARDING_CONTROL)
    {"L2_CAM_CB_MC"},
    {"L2_CAM_CB_UC"},
    {"L2_CAM_MC"},
    {"L2_CAM_UC"},
    {"L2_CB_MC"},
    {"L2_CB_UC"},
    {"L2_MC"},
    {"L2_UC"},
    {"MC_PMSK"},
#endif   /* CONFIG_SDK_CHIP_FEATURE_MAC_FORWARDING_CONTROL */
#if defined(CONFIG_SDK_CHIP_FEATURE_EGRESS_BANDWIDTH_CONTROL)
    {"EGR_Q_BW"},
#endif   /* CONFIG_SDK_CHIP_FEATURE_EGRESS_BANDWIDTH_CONTROL */
#if defined(CONFIG_SDK_CHIP_FEATURE_METER_MARKER)
    {"METER"},
#endif   /* CONFIG_SDK_CHIP_FEATURE_METER_MARKER */
#if defined(CONFIG_SDK_CHIP_FEATURE_FLOWCONTROL___BACKPRESSURE)
    {"OUT_Q"},
#endif   /* CONFIG_SDK_CHIP_FEATURE_FLOWCONTROL___BACKPRESSURE */
#if defined(CONFIG_SDK_CHIP_FEATURE_REMARKING)
    {"REMARK"},
#endif   /* CONFIG_SDK_CHIP_FEATURE_REMARKING */
#if defined(CONFIG_SDK_CHIP_FEATURE_LAYER_3_ROUTING)
    {"L3_ECMP"},
    {"L3_EGR_INTF"},
    {"L3_EGR_INTF_CNTR"},
    {"L3_EGR_INTF_LIST"},
    {"L3_EGR_TUNNEL_INTF_CNTR"},
    {"L3_HOST_ROUTE_IP6MC_0"},
    {"L3_HOST_ROUTE_IP6MC_1"},
    {"L3_HOST_ROUTE_IP6MC_2"},
    {"L3_HOST_ROUTE_IP6MC_3"},
    {"L3_HOST_ROUTE_IP6MC_4"},
    {"L3_HOST_ROUTE_IP6MC_5"},
    {"L3_HOST_ROUTE_IP6UC_0"},
    {"L3_HOST_ROUTE_IP6UC_1"},
    {"L3_HOST_ROUTE_IP6UC_2"},
    {"L3_HOST_ROUTE_IPMC_0"},
    {"L3_HOST_ROUTE_IPMC_1"},
    {"L3_HOST_ROUTE_IPUC"},
    {"L3_IGR_INTF"},
    {"L3_IGR_INTF_CNTR"},
    {"L3_IGR_TUNNEL_INTF_CNTR"},
    {"L3_NEXTHOP"},
    {"L3_PREFIX_ROUTE_IP6MC_0"},
    {"L3_PREFIX_ROUTE_IP6MC_1"},
    {"L3_PREFIX_ROUTE_IP6MC_2"},
    {"L3_PREFIX_ROUTE_IP6MC_3"},
    {"L3_PREFIX_ROUTE_IP6MC_4"},
    {"L3_PREFIX_ROUTE_IP6MC_5"},
    {"L3_PREFIX_ROUTE_IP6UC_0"},
    {"L3_PREFIX_ROUTE_IP6UC_1"},
    {"L3_PREFIX_ROUTE_IP6UC_2"},
    {"L3_PREFIX_ROUTE_IPMC_0"},
    {"L3_PREFIX_ROUTE_IPMC_1"},
    {"L3_PREFIX_ROUTE_IPUC"},
    {"L3_ROUTER_MAC"},
#endif   /* CONFIG_SDK_CHIP_FEATURE_LAYER_3_ROUTING */
#if defined(CONFIG_SDK_CHIP_FEATURE_IP_TUNNEL)
    {"TUNNEL_START"},
    {"TUNNEL_START_ENCAP"},
    {"TUNNEL_START_ENCAP_1"},
    {"TUNNEL_START_ENCAP_2"},
    {"TUNNEL_TERMINATION"},
    {"TUNNEL_TERMINATION_1"},
    {"TUNNEL_TERMINATION_2"},
#endif   /* CONFIG_SDK_CHIP_FEATURE_IP_TUNNEL */
#if defined(CONFIG_SDK_CHIP_FEATURE_MPLS_VPLS)
    {"MPLS_DECAP"},
    {"MPLS_DECAP_CAM"},
    {"MPLS_ENCAP"},
    {"MPLS_NH"},
#endif   /* CONFIG_SDK_CHIP_FEATURE_MPLS_VPLS */
#if defined(CONFIG_SDK_CHIP_FEATURE_MIB_COUNTER)
    {"STAT_PORT_MIB_CNTR"},
#endif   /* CONFIG_SDK_CHIP_FEATURE_MIB_COUNTER */
#if defined(CONFIG_SDK_CHIP_FEATURE_FLOW_BASED_COUNTER)
    {"FLOW_CNTR"},
#endif   /* CONFIG_SDK_CHIP_FEATURE_FLOW_BASED_COUNTER */
#if defined(CONFIG_SDK_CHIP_FEATURE_PRIVATE_COUNTER)
    {"AUTO_RECOVERY_TXERR_CNT"},
    {"STAT_PORT_PRVTE_CNTR"},
    {"STAT_PORT_PRVTE_E_Q_CNTR"},
#endif   /* CONFIG_SDK_CHIP_FEATURE_PRIVATE_COUNTER */
#if defined(CONFIG_SDK_CHIP_FEATURE_ACL)
    {"EACL"},
    {"IACL"},
    {"VACL"},
#endif   /* CONFIG_SDK_CHIP_FEATURE_ACL */
#if defined(CONFIG_SDK_CHIP_FEATURE_IP_MAC_BIDING)
    {"IP_MAC_BIND"},
    {"IP_MAC_BIND_CAM"},
    {"IP_MAC_BIND_DYN"},
#endif   /* CONFIG_SDK_CHIP_FEATURE_IP_MAC_BIDING */
#if defined(CONFIG_SDK_CHIP_FEATURE_OPENFLOW)
    {"ACTION_BUCKET"},
    {"FT_EGR"},
    {"FT_IGR"},
    {"FT_L2_CAM_FMT0_0"},
    {"FT_L2_CAM_FMT0_1"},
    {"FT_L2_CAM_FMT1_0"},
    {"FT_L2_CAM_FMT1_1"},
    {"FT_L2_CAM_FMT2_0"},
    {"FT_L2_HASH_FMT0_0"},
    {"FT_L2_HASH_FMT0_1"},
    {"FT_L2_HASH_FMT1_0"},
    {"FT_L2_HASH_FMT1_1"},
    {"FT_L2_HASH_FMT2_0"},
    {"FT_L2_HASH_FMT2_1"},
    {"FT_L3_HASH_0"},
    {"FT_L3_HASH_1"},
    {"FT_L3_HASH_2"},
    {"FT_L3_TCAM_0"},
    {"FT_L3_TCAM_1"},
    {"FT_L3_TCAM_2"},
    {"GROUP_TBL"},
    {"OF_DMAC"},
#endif   /* CONFIG_SDK_CHIP_FEATURE_OPENFLOW */
#if defined(CONFIG_SDK_CHIP_FEATURE_L2_TUNNEL)
    {"BSSID"},
    {"BSSID_CAM"},
    {"BSSID_LIST"},
    {"BSSID_TUNNEL_START"},
    {"CAPWAP_TUNNEL_START_0"},
    {"CAPWAP_TUNNEL_START_1"},
    {"L2_TNL_LST"},
    {"L2_TNL_MCAST"},
    {"L2_TNL_MCAST_CAM"},
    {"L2_TNL_UCAST"},
    {"L2_TNL_UCAST_CAM"},
    {"L2_TNL_VXLAN"},
    {"L2_TNL_VXLAN_CAM"},
    {"L2_TNL_VXLAN_ENCAP"},
    {"VXLAN_TUNNEL_START_0"},
    {"VXLAN_TUNNEL_START_1"},
    {"WLC_MCAST"},
    {"WLC_MCAST_CAM"},
    {"WLC_UCAST"},
    {"WLC_UCAST_CAM"},
#endif   /* CONFIG_SDK_CHIP_FEATURE_L2_TUNNEL */
#if defined(CONFIG_SDK_CHIP_FEATURE_PORT_EXTENSION)
    {"ECID_PMSK_LIST"},
    {"ECID_PVID"},
    {"ECID_PVID_CAM"},
    {"PE_FWD"},
    {"PE_FWD_CAM"},
#endif   /* CONFIG_SDK_CHIP_FEATURE_PORT_EXTENSION */
};
#endif  /* CONFIG_SDK_DUMP_TABLE_WITH_NAME */

