#
#Copyright (C) 2007-2008 Industrie Dial Face S.p.A.
#Luigi 'Comio' Mantellini (luigi.mantellini@idf-hit.com)
#
#(C) Copyright 2003-2006
#Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
#SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_TARGET_PRESIDIO_ASIC) += g3_cortex_freq.o
obj-$(CONFIG_TARGET_VENUS) += cmd_cortex_freq.o venus_cortex_freq.o
