/*
 * Automatically generated C config: don't edit
 */
#define AUTOCONF_INCLUDED

/*
 * Chip Support
 */

/*
 * Select your target MAC chip(s)
 */
#undef  CONFIG_SDK_RTL9310
#define CONFIG_SDK_RTL9300 1
#undef  CONFIG_SDK_RTL8390
#undef  CONFIG_SDK_RTL8380

/*
 * Select your target PHYs chip
 */
#undef  CONFIG_SDK_RTL8208D
#undef  CONFIG_SDK_RTL8208G
#undef  CONFIG_SDK_RTL8208L
#undef  CONFIG_SDK_RTL8212B
#undef  CONFIG_SDK_RTL8214B
#undef  CONFIG_SDK_RTL8214FB
#undef  CONFIG_SDK_RTL8214FC
#undef  CONFIG_SDK_RTL8214C
#define CONFIG_SDK_RTL8214QF 1
#undef  CONFIG_SDK_RTL8218B
#define CONFIG_SDK_RTL8218D 1
#define CONFIG_SDK_RTL8218E 1
#undef  CONFIG_SDK_RTL8218FB
#undef  CONFIG_SDK_RTL8224QF
#define CONFIG_SDK_RTL8226 1
#define CONFIG_SDK_RTL8295R 1
#undef  CONFIG_SDK_RTL826X
#undef  CONFIG_SDK_RTL826XI
#undef  CONFIG_SDK_RTL825X
#undef  CONFIG_SDK_RTL825XI
#undef  CONFIG_SDK_RTL825XL
#define CONFIG_SDK_RTL8224 1
#define CONFIG_SDK_RTL826XB 1

/*
 * Select your target Peripheral chip
 */
#define CONFIG_SDK_RTL8231 1

/*
 * Select customer defined PHYs chip
 */
#undef  CONFIG_SDK_PHY_CUST1
#undef  CONFIG_SDK_PHY_CUST2
#undef  CONFIG_SDK_PHY_CUST3
#undef  CONFIG_SDK_PHY_CUST4
#undef  CONFIG_SDK_PHY_CUST5
#define CONFIG_SDK_EXPERIMENTAL_RTL8211FS 1

/*
 * CPU
 */
#undef  CONFIG_SDK_EXTERNAL_CPU
#undef  CONFIG_SDK_ENDIAN_LITTLE

/*
 * Operating System
 */
#define CONFIG_SDK_KERNEL_LINUX 1
#undef  CONFIG_SDK_OS_KERNEL_OTHER
#undef  CONFIG_SDK_KERNEL_LINUX_KERNEL_MODE
#define CONFIG_SDK_KERNEL_LINUX_USER_MODE 1
#define CONFIG_SDK_KERNEL_LINUX_MODULE_LOADABLE 1

/*
 * SDK Driver
 */

/*
 * Rtcore Driver support
 */
#undef  CONFIG_SDK_DRIVER_RTCORE
#define CONFIG_SDK_DRIVER_RTCORE_MODULE 1
#define CONFIG_SDK_DRIVER_RTCORE_IN_LINUX_KERNEL 1
#define CONFIG_SDK_DRIVER_NIC 1
#undef  CONFIG_SDK_DRIVER_EXTC_NIC
#undef  CONFIG_SDK_DRIVER_EXTC_PCI
#define CONFIG_SDK_DRIVER_GPIO 1
#define CONFIG_SDK_DRIVER_SPI 1
#define CONFIG_SDK_DRIVER_I2C 1
#define CONFIG_SDK_TC_DRV 1
#define CONFIG_SDK_DRIVER_WATCHDOG 1
#define CONFIG_SDK_TC_TC1_TIME 1
#define CONFIG_SDK_UART1 1
#define CONFIG_SDK_BSP_USBHCD 1
#undef  CONFIG_SDK_DRIVER_NIC_KERNEL_MODE
#define CONFIG_SDK_DRIVER_NIC_USER_MODE 1
#undef  CONFIG_SDK_DRIVER_NIC_R9310
#define CONFIG_SDK_DRIVER_NIC_R9300 1
#undef  CONFIG_SDK_DRIVER_NIC_R8390
#undef  CONFIG_SDK_DRIVER_NIC_R8380
#define CONFIG_SDK_DRIVER_L2NTFY 1
#undef  CONFIG_SDK_DRIVER_L2NTFY_R9310
#define CONFIG_SDK_DRIVER_L2NTFY_R9300 1
#undef  CONFIG_SDK_DRIVER_L2NTFY_R8390
#undef  CONFIG_SDK_DRIVER_I2C_R9310
#define CONFIG_SDK_DRIVER_I2C_R9300 1
#undef  CONFIG_SDK_DRIVER_I2C_R8390
#undef  CONFIG_SDK_DRIVER_I2C_R8380

/*
 * Rtk Driver / RTK API support
 */
#define CONFIG_SDK_DRIVER_RTK 1
#undef  CONFIG_SDK_DRIVER_RTK_LEGACY_API
#define CONFIG_SDK_DRIVER_RTK_CUSTOMER 1
#define CONFIG_SDK_DRIVER_RTK 1
#define CONFIG_SDK_DRIVER_RTK_CUSTOMER 1
#undef  CONFIG_SDK_DRIVER_MX
#undef  CONFIG_SDK_DRIVER_COMPILE
#define CONFIG_SDK_DRIVER_COMPILE_MODULE 1

/*
 * SDK Application
 */
#define CONFIG_SDK_APP_DIAG 1
#define CONFIG_SDK_APP_DIAG_DIR_DIAG_V2 1
#undef  CONFIG_SDK_APP_DIAG_EXT
#undef  CONFIG_SDK_SQUT_CMD_OPT
#define CONFIG_SDK_APP_COMPILE 1

/*
 * SDK Debug
 */
#define CONFIG_SDK_DEBUG 1
#define CONFIG_SDK_DEBUG_LOG_TYPE_LEVEL 1
#undef  CONFIG_SDK_DEBUG_LOG_TYPE_LEVEL_MASK
#define CONFIG_SDK_DEBUG_LOG_LEVEL 3
#define CONFIG_SDK_DEBUG_LOG_MOD_MASK 0xFFFFFFFFFFFFFFFFULL
#undef  CONFIG_SDK_DUMP_REG_WITH_NAME
#undef  CONFIG_SDK_DUMP_TABLE_WITH_NAME

/*
 * BSP Option
 */
#define CONFIG_SDK_BSP_FLASH 1
#define CONFIG_FLASH_LAYOUT_TYPE5 1
#define CONFIG_TURNKEY_SYSINFO 1
#define CONFIG_DUAL_IMAGE 1
#define CONFIG_ENV_MTD_INDEX 0x1
#define CONFIG_ENV2_MTD_INDEX 0x2
#define CONFIG_BDINFO_MTD_INDEX 0x3
#define CONFIG_SDK_BSP_MTD 1
#define CONFIG_SDK_BSP_MTD_SPI 1
#undef  CONFIG_SDK_BSP_MTD_NOR
#define CONFIG_SDK_BSP_MTD_SPIM 1
#define CONFIG_SDK_BSP_MTD_NORSF_G3 1
#define CONFIG_SDK_BSP_MTD_COMMON 1
#undef  CONFIG_SDK_BSP_MTD_RTK_SPI_NAND
#define CONFIG_SDK_BSP_MTD_SPI_NAND_G3 1
#define CONFIG_SDK_BSP_MTD_ECC_G2 1
#define CONFIG_SDK_SPI_DEV_NONE 1
#undef  CONFIG_SDK_SPI_DEV_1
#undef  CONFIG_SDK_SPI_DEV_2
#undef  CONFIG_SDK_SPI_DEV_3
#undef  CONFIG_SDK_SPI_DEV_4
#undef  CONFIG_SDK_SPI_DEV_5
#define CONFIG_SDK_BSP_SPI_NOR_BOOT 1
#undef  CONFIG_SDK_BSP_SPI_NAND_BOOT

/*
 * Misc Option
 */
#undef  CONFIG_SDK_EXPERIMENTAL
#undef  CONFIG_SDK_FPGA_PLATFORM
#undef  CONFIG_SDK_DRIVER_TEST
#undef  CONFIG_SDK_MODEL_MODE
#undef  CONFIG_SDK_LINKED_KMOD
#undef  CONFIG_TRUNK_FAILOVER_HANDLING
#undef  CONFIG_SDK_RX_THREAD
#define CONFIG_SDK_LINKMON_POLLING_MODE 1
#undef  CONFIG_SDK_LINKMON_ISR_MODE
#undef  CONFIG_SDK_LINKMON_MIXED_MODE
#undef  CONFIG_RISE
#undef  CONFIG_SDK_HW_PROFILE_PROBE_GPIO
#define CONFIG_SDK_HW_PROFILE_PROBE_UBOOT_ENV 1
#define CONFIG_SDK_OS_VERSION "Linux 3.18.24"
#define CONFIG_SDK_COMPILER_VERSION "GCC 4.8.5"
#define CONFIG_SDK_LIBC_VERSION "uClibc-0.9.33.2 with NPTL"
